INSERT INTO LITERAL VALUES(NULL,'ES','NODIR','Directorio no encontrado.');
INSERT INTO LITERAL VALUES(NULL,'CAT','NODIR','Directori no trobat.');
INSERT INTO LITERAL VALUES(NULL,'ENG','NODIR','The directory dosen´t exist.');

INSERT INTO LITERAL VALUES(NULL,'ES','NOTAVALIDCOMMAND','El comando no existe.');
INSERT INTO LITERAL VALUES(NULL,'CAT','NOTAVALIDCOMMAND','El commandament no existeix.');
INSERT INTO LITERAL VALUES(NULL,'ENG','NOTAVALIDCOMMAND','This command dosen´t exist.');

INSERT INTO LITERAL VALUES(NULL,'ES','WRONGARGNUM','Numero de argumentos incorrecto.');
INSERT INTO LITERAL VALUES(NULL,'CAT','WRONGARGNUM','Nombre d´arguments incorrecte.');
INSERT INTO LITERAL VALUES(NULL,'ENG','WRONGARGNUM','Wrong number of arguments.');

INSERT INTO LITERAL VALUES(NULL,'ES','MISSINGARGS','Faltan argumentos.');
INSERT INTO LITERAL VALUES(NULL,'CAT','MISSINGARGS','Falten arguments.');
INSERT INTO LITERAL VALUES(NULL,'ENG','MISSINGARGS','Missing arguments.');

INSERT INTO LITERAL VALUES(NULL,'ES','UNCATALOGUED','Error no catalogado.');
INSERT INTO LITERAL VALUES(NULL,'CAT','UNCATALOGUED','Error no catalogat.');
INSERT INTO LITERAL VALUES(NULL,'ENG','UNCATALOGUED','Uncatalogued error');

INSERT INTO LITERAL VALUES(NULL,'ES','INSERTCOMMAND','Inserta comando: ');
INSERT INTO LITERAL VALUES(NULL,'CAT','INSERTCOMMAND','Inserta commandament: ');
INSERT INTO LITERAL VALUES(NULL,'ENG','INSERTCOMMAND','Insert command: ');

INSERT INTO LITERAL VALUES(NULL,'ES','CREATEDCORRECTLY','Creado correctamente.');
INSERT INTO LITERAL VALUES(NULL,'CAT','CREATEDCORRECTLY','Creat correctament.');
INSERT INTO LITERAL VALUES(NULL,'ENG','CREATEDCORRECTLY','Created correctly.');

INSERT INTO LITERAL VALUES(NULL,'ES','DELETEDCORRECTLY','Eliminado correctamente.');
INSERT INTO LITERAL VALUES(NULL,'CAT','DELETEDCORRECTLY','Eliminat correctament.');
INSERT INTO LITERAL VALUES(NULL,'ENG','DELETEDCORRECTLY','Deleted correctly.');

INSERT INTO LITERAL VALUES(NULL,'ES','EXIT','Fin del programa.');
INSERT INTO LITERAL VALUES(NULL,'CAT','EXIT','Fi del programa.');
INSERT INTO LITERAL VALUES(NULL,'ENG','EXIT','Program finished.');

INSERT INTO LITERAL VALUES(NULL,'ES','LOG','Logs activados.');
INSERT INTO LITERAL VALUES(NULL,'CAT','LOG','Logs activats.');
INSERT INTO LITERAL VALUES(NULL,'ENG','LOG','Logs activated.');

INSERT INTO LITERAL VALUES(NULL,'ES','NOLOG','Logs desactivados.');
INSERT INTO LITERAL VALUES(NULL,'CAT','NOLOG','Logs desactivats.');
INSERT INTO LITERAL VALUES(NULL,'ENG','NOLOG','Logs switched off.');

